name: PVS-Studio C++ Static Analysis

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt \
            | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/pvs-studio.gpg --import
          sudo chmod 644 /etc/apt/trusted.gpg.d/pvs-studio.gpg
          sudo wget -O /etc/apt/sources.list.d/viva64.list \
            https://files.pvs-studio.com/etc/viva64.list
          sudo apt-get update
          sudo apt-get install -y pvs-studio cmake build-essential

      - name: Activate PVS-Studio License
        run: pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}

      - name: Build project
        run: |
          mkdir -p C++/build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Unix Makefiles" -S C++ -B C++/build
          cmake --build C++/build

      - name: Analyze
        run: |
          pvs-studio-analyzer analyze -f C++/build/compile_commands.json -o C++/build/pvs.log -j

      - name: Convert report to SARIF
        run: |
          plog-converter -t sarif -o pvs-studio-report.sarif -a ALL C++/build/pvs.log

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: pvs-studio-report.sarif
          category: pvs-studio
